services:
  - type: web
    name: skywave
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: false
  
  - type: pserv
    name: skywave-db
    ipAllowList: []
    plan: free
    region: oregon
    version: 14
